function createfigure(ts1, YMatrix1)
%CREATEFIGURE(ts1, YMatrix1)
%  TS1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 06-May-2026 10:21:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.106796116504854 0.116342494714588 0.763899676375404 0.839260042283298]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(ts1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Elektronik',...
    'Color',[0.752941176470588 0.36078431372549 0.984313725490196]);
set(plot1(2),'DisplayName','Radiator','Color',[1 0.075 0.651]);
set(plot1(3),'DisplayName','Ramme','Color',[0.996 0.2 0.039]);
set(plot1(4),'DisplayName','PCM','Color',[0.133 0.71 0.451]);

% Create ylabel
ylabel('Temperatur (K)','FontSize',15);

% Create xlabel
xlabel('Tid (s)','FontSize',15);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 30000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[292 305]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'TickDir','out','XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.748602115716754 0.812415155947793 0.0895833333333347 0.128405512357683],...
    'Interpreter','none',...
    'FontSize',15);

% Create textarrow
annotation(figure1,'textarrow',[0.768782383419689 0.801165803108808],...
    [0.385835095137421 0.569767441860465],'String','Steady state','FontSize',20);

% Create textarrow
annotation(figure1,'textarrow',[0.378238341968912 0.128886010362695],...
    [0.176532769556025 0.175475687103595],'String','Initierende værdier',...
    'FontSize',20);

